id: P49D5DF22
initial_creation_type: input
source_metadata:
  title: Fifth Dodrupchen Rinpoche Series
  language: bo
  description: 'Texts by and about the Fifth Dodrupchen Rinpoche, Jigme Long-yang
    (''jigs med klong yangs, b. 1962):'
  volume:
    2a31241a31c54eba976f7d17315453da:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:14:32.338214'
last_modified_at: '2022-02-28T23:14:32.338217'
statistics:
  total_words: 235
  total_non_words: 20
quality:
  non_words_ratio: 0.09
